# Sample dictionary of diseases and their symptoms
disease_symptoms = {
    
     # Diseases starting with "A"
    
    'Abnormal heart rhythms (arrhythmia)': [
        'shortness of breath',
        'chest pain',
        'irregular pulse',
        'heart palpitations',
        'sweating',
        'pale color of skin',
    ],
    'Acidity': [
        'nausea',
        'burning sensation in the chest',
        'burping',
        'vomiting tendency',
        'chest pain',
        'sensation of a lump in your throat',
        'difficulty swallowing',
        'bloating',
        'severe pain in the stomach',
        'difficulty in breathing when acidity is at the acute stage',
        'due to hyper acidity there is erosion of gum and teeth',
        'bad breath',
    ],
    'Acid reflux': [
        'heartburn',
        'regurgitation',
        'gas bloating',
        'bloody or black colored stools',
        'bloody vomiting',
        'burping and hiccups',
        'dysphagia i.e. difficulty in swallowing',
        'nausea',
        'unexpected weight loss',
        'wheezing (the sound of a high-pitched whistle while breathing)',
        'dry cough',
        'hoarseness or chronic sore throat',
    ],
    'Acne': [
        'whiteheads or the closed plugged pores',
        'blackheads or open plugged pores',
        'small and red colored tender bumps on the affected area',
        'pimples with pus at their tips',
        'large painful lumps that are present beneath the skin surface',
        'presence of pus-filled lumps beneath the surface of the skin, also known as cystic lesions',
    ],
    'Agoraphobia': [
        'rapid breathing',
        'rapid heartbeat',
        'excessive sweating',
        'feeling too much hot',
        'feeling sick',
        'tingling sensation and numbness',
        'pain in the chest',
        'dizziness or light-headedness',
        'chills and sudden flushes',
        'diarrhea',
        'upset stomach',
        'fear of death',
        'losing control',
        'afraid to be alone',
        'afraid to be in the crowd',
        'scared to leave home alone',
        'too much dependence on others',
        'feeling of helplessness',
        'loss of sanity',
        'fear of staying alone',
        'feeling of anxiety and fear',
        'always staying at home',
        'always feeling the need to be with a trusted individual',
    ],
    'Allergic bronchitis': [
        'mucus-producing cough (clear mucus or white)',
        'recurring morning cough',
        'fatigue',
        'sinus congestion or postnasal drip',
        'bad breath (halitosis)',
        'wheezing/ whistling sound during breathing',
        'shortness of breath (dyspnea)',
        'chest tightness',
    ],
    'Allergic rhinitis': [
        'sneezing',
        'running nose',
        'itching on the nose, eyes as well as on the roof of the mouth',
        'conjunctivitis- redness and swelling in the eyes',
    ],
    'Food allergy': [
        'swelling in the lips, tongue as well as on the face',
        'hives',
        'tingling mouth',
        'anaphylaxis',
        'throat swelling',
    ],
    'Insect sting allergy': [
        'swelling on the sting site',
        'itching all over the body',
        'hives',
        'cough and chest tightness',
        'anaphylaxis',
        'wheezing or shortness of breath',
    ],
    'Drug allergy': [
        'hives',
        'itching all over the skin',
        'rash as well as redness',
        'swelling on the face',
        'shortness of breath',
    ],
    'Skin allergy': [
        'itching',
        'redness',
        'rashes',
        'flake or peel of skin',
    ],
    'Alopecia (hair loss)': [
        'presence of circular patches or bald spots',
        'sudden loss of hair',
        'thinning of hair',
        'partial or full body hair loss',
    ],
    'Alzheimer\'s disease': [
        'loss of memory',
        'difficulty in concentrating and thinking',
        'difficulty in performing daily basic tasks such as bathing or dressing etc.',
        'changes in personality',
        'changes in behavior',
        'depression and mood swings',
        'wandering',
        'aggressive behavior',
        'irritation',
    ],
    'Amyloidosis': [
        'swelling in the ankles and legs',
        'fatigue',
        'weakness',
        'shortness of breath',
        'diarrhea and constipation',
        'pain in hands and feet',
        'an enlarged tongue',
        'feeling of fullness after eating',
        'an irregular heartbeat',
        'skin discoloration',
        'weight loss',
    ],
    'Anaemia': [
        'tiredness and weakness on little exertion',
        'paleness and dullness of skin',
        'shortness of breath',
        'increase in heartbeat',
        'confusion and dizziness',
        'insomnia',
        'cold and clammy hands',
        'body aches',
        'fatigue',
        'restlessness',
        'lack of energy',
        'irritable behavior',
    ],
    'Anal fistula': [
        'pain which is usually throbbing, constant, worsen in sitting position',
        'discharge of pus and blood',
        'constipation or pain associated with bowel movement',
        'fever',
    ],
    'Anemia': [
        'pale skin',
        'weakness',
        'fatigue',
        'tiredness',
        'chest pain',
        'chest pain',
        'headache',
    ],
    'Angina pectoris': [
        'nausea',
        'sweating',
        'fatigue',
        'breathlessness',
        'anxiety',
        'dizziness',
        'discomfort and pain in back, neck and shoulders',
        'chest pain',
    ],
    'Ankylosing spondylitis': [
        'pain and stiffness in lower back and hip region',
    ],
    'Anorexia nervosa': [
        'refuse to eat certain food',
        'constipation',
        'abdominal pain',
        'cold intolerance',
        'not feeling hungry often',
        'weight loss',
        'cooks meals for others without eating',
        'limited social spontaneity',
        'intense fear of weight gain',
        'shows flexible thinking',
        'follows strict diet and exercise routine',
        'dry skin',
        'dry and brittle nails',
        'fine hair on body',
        'muscle weakness',
        'feeling cold all the time',
        'fainting, sleep problems, feeling dizziness all the time',
        'difficulty in concentrating',
        'poor immune system',
        'thinning of hair on head',
    ],
    'Anxiety': [
        'improper sleep',
        'muscle tension',
        'chronic indigestion',
        'stage fear',
        'self consciousness',
        'panic',
        'flashbacks',
        'perfectionism',
        'compulsive behavior',
        'self-doubt',
    ],
    'Arthritis': [
        'pain in the joints',
        'inflammation in the joints',
        'stiffness, swelling, redness and warmth in the joints',
        'tenderness in the inflamed joints',
        'sometimes, fever, weight loss and fatigue',
    ],
    'Ascites': [
        'increased abdominal girth and size',
        'pain in the abdomen',
        'discomfort and bloating',
    ],
    'Asherman\'s syndrome': [
        'menstrual irregularities such as very light periods (hypo menorrhea) or absence of periods (amenorrhea)',
        'may lead to infertility due to adhesions including the uterus and fallopian tubes',
        'recurrent pregnancy loss (miscarriage)',
        'pelvic pain, if scar tissue blocks the outflow of the menstrual blood, causing uterine cramping and pelvic discomfort or pain',
    ],
    'Asthma': [
        'coughing - coughing from asthma worsen at night and early in the morning, and make it hard to sleep',
        'wheezing - wheezing is a whistling sound occurs when you breathe',
        'chest tightness - this may feel like something is squeezing your chest',
        'shortness of breath - someone who have asthma cannot catch their breath, you may feel like you cannot get air out of your lungs',
        'trouble in sleeping due to wheezing, chest tightness and coughing',
        'not all people who have asthma have these symptoms, having these symptoms not always means that you have asthma. sometimes symptoms just annoy you, or troublesome to your daily routine',
        'severe symptoms can be fatal. it\'s important to treat symptoms when you first notice them otherwise they become fatal',
    ],
    'Atopic dermatitis': [
        'itching, which can be severe, at night especially',
        'red to brownish-gray patches, especially on the neck, upper chest, eyelids, inside the bend of the elbows hands, feet, ankles, wrists, and knees. in the case of infants, these patches form on face and scalp',
        'burning sensation or pain on the skin',
        'skin becomes dry, red, scaly, thickened and rough',
        'fissures in the skin',
        'inflammation of the skin',
        'lumps formed on skin and there is the leakage of fluid',
    ],
    'Atrial fibrillation': [
        'rapid heart rate',
        'heart palpitations',
        'shortness of breath (while lying flat or sudden onset during night)',
        'light headedness',
        'dizziness',
        'confusion',
        'fainting',
        'chest pain',
        'increased risk for heart failure, dementia and stroke',
        'swelling in lower extremities',
        'respiratory distress due to congestion of lungs',
    ],
    'Autism': [
        'lines up toys or other objects',
        'plays with toys the same way every time',
        'has to follow certain routines',
        'likes parts of objects',
        'is very organized',
        'flaps hands, rocks body, or spins self in circles',
        'does not point or respond to pointing',
        'does not understand jokes or teasing',
        'talks in a flat, robot-like, or sing-song voice',
        'gives unrelated answers to questions',
        'delayed speech and language skills',
        'uses few or no gestures (e.g., does not wave goodbye)',
    ],
    'Autoimmune disorder': [
        'fever',
        'fatigue',
        'joint pain',
        'malaise',
    ],
    
    # Diseases starting with "B"
    
    'Back pain': [
        'weight loss',
        'fever',
        'inflammation or swelling on the back',
        'pain down the legs',
        'pain that reaches below the knees',
        'difficulty urinating',
        'recent injury to the back',
        'back pain which causes difficulty in lying down',
        'numbness around the genitals',
        'numbness around the buttocks',
        'numbness around the anus',
    ],
    'Bacterial vaginosis': [
        'vaginal discharge',
        'vaginal odor',
        'itching around the vagina',
        'burning sensation while urination',
    ],
    'Baldness': [
        'hair loss in patches',
        'dandruff',
        'skin lesions',
        'scarring',
        'thinning of hair',
    ],
    'Bedwetting': [
        'passing urine during day or night sleep',
    ],
    'Bell\'s palsy': [
        'facial paralysis and no control over facial muscles',
        'unable to taste or loses sense of taste',
        'feeling weakness of the muscles and nerves in the facial region',
        'difficulty in closing eyes',
        'pain in and outside ears',
        'numbness of the jaws, forehead, cheek, mouth region',
        'blurred view',
        'in an attempt to raise eyebrows, the forehead region affected by bell\'s palsy remains flat',
        'smiling distorts the face of the patient',
    ],
    'Benign prostatic hyperplasia (bph)': [
        'urinary frequency',
        'urinary urgency',
        'hesitancy',
        'incomplete bladder emptying',
        'straining',
        'disturbed sleep at night',
        'decreased force of stream',
        'dribbling',
    ],
    'Wet beriberi': [
        'increase in heart rate',
        'swollen lower legs',
        'waking up short of breath',
        'shortness of breath during physical activity',
    ],
    'Dry beriberi': [
        'paralysis',
        'involuntary eye movement',
        'vomiting',
        'difficulty in breathing',
        'pain',
        'mental confusion',
        'tingling in feet and hands',
        'decreased muscle function',
    ],
    'Bipolar mania': [
        'excitement',
        'talkativeness',
        'impulsive behavior',
        'overactivity',
        'racing thoughts',
        'reduced need for sleep',
    ],
    'Bipolar hypomania': [
        'aggression or anger',
        'overconfidence',
        'irritability',
        'decreased need for sleep',
        'hyperactivity',
    ],
    'Bipolar depression': [
        'sadness',
        'hopelessness',
        'loss of interest or pleasure in most activities',
        'fatigue',
        'difficulty concentrating',
        'change in appetite or weight',
        'thoughts of death or suicide',
    ],
    'Bipolar mixed episodes': [
        'symptoms of both mania and depression occurring simultaneously',
        'agitation',
        'irritability',
        'trouble sleeping',
        'change in appetite or weight',
    ],
    'Blood clotting': [
        'swelling',
        'pain',
        'tenderness',
        'redness',
        'warm sensation',
    ],
    'Blood disorders': [
        'blood clot (phlebitis)',
        'skin rashes caused by few platelets (petechiae)',
        'blood blisters in mouth',
        'swelling of lymph nodes due to blood cancer like leukemia, lymphomas',
        'yellowish skin (pallor) caused by anemia',
        'eating of ice, dirt, clay (pica) due to iron deficiency anemia',
    ],
    'Bronchitis': [
        'constant cough with mucus',
        'difficulty in breathing',
        'fever',
        'wheezing',
        'chest discomfort',
    ],
    'Bulged disc': [
        'pain in arms and legs',
        'numbness',
        'weakness',
    ],

    # Diseases starting with "C"
    
    'Cancer': [
        'fever',
        'fatigue',
        'pain',
        'unusual bleeding',
        'nagging cough',
        'indigestion problems or trouble swallowing.',
        'unexplained weight loss',
        'skin changes',
    ],
    'Candidiasis': [
        'redness',
        'itching',
        'swelling',
        'rashes',
        'burning sensation',
    ],
    'Cataract': [
        'blurred vision',
        'difficulty with vision at night',
        'double vision',
        'problem differentiating colors',
        'sensitivity to light',
        'seeing "halos" around lights',
        'fading or yellowing of colors',
        'frequent changes in eyeglass or contact lens prescription',
    ],
    'Cerebral palsy': [
        'difficulty in movement',
        'ataxia (lack of muscle coordination)',
        'variation in muscle tone',
        'involuntary movements',
        'rigidity',
        'problem in feeding and sucking',
        'difficulty in eyesight, hearing or speaking',
        'athetosis (slow, writhing problems)',
        'spasticity (severe tightening of muscle)',
    ],
    'Cerebral stroke': [
        'depression',
        'double vision',
        'headache',
        'dizziness',
        'weakness on one or both sides of the body',
        'trouble in walking, speaking or understanding',
        'paralysis on face',
    ],
    'Cervical dystonia': [
        'cramps in the legs',
        'neck pull involuntarily',
        'blinking of the eyes in an uncontrolled manner',
        'difficulties in speech',
        'dragging of legs',
        'fatigue',
        'exhaustion',
        'stress',
        'pain',
    ],
    'Cervical spondylosis': [
        'standing',
        'sitting',
        'sneezing',
        'coughing',
        'tilting your neck backward',
    ],
    'Cholera': [
        'rice water stools',
        'leg cramps',
        'vomiting',
        'loose skin',
        'sunken eyes',
        'fast heart beat',
        'low blood pressure',
        'massive weight loss',
        'dry mouth',
        'collapse of the circulatory system',
    ],
    'Chronic fatigue syndrome': [
        'muscle pain',
        'fatigue',
        'memory loss',
        'confusion',
        'anxiety and depression',
        'stroke',
        'trauma',
        'joint pain',
    ],
    'Constipation': [
        'pain during passing stool',
        'bleeding during stools',
        'abdominal pain',
        'indigestion',
        'heaviness of body',
        'loss of appetite',
        'dry and difficult bowel movement',
        'feeling uncomfortable',
    ],
    'Crohn\'s disease': [
        'diarrhea',
        'fatigue',
        'abdominal pain',
        'abdominal cramps',
        'loss of appetite',
        'weight loss',
        'general weakness',
        'fever',
        'mucus',
        'pain and drainage around the anal region',
        'mouth sores',
        'blood in stool',
        'it may cause inflammation of eyes, skin, and joints.',
        'in children, it leads to delayed growth or sexual development.',
        'sometimes it may cause inflammation of the liver and bile ducts.',
    ],
    'Cystitis': [
        'frequent urge of urination',
        'burning sensation while urinating',
        'fever',
        'blood in urine (hematuria)',
        'pain during sexual intercourse',
        'pressure on the lower abdomen',
        'cloudy and strong-smelling urine',
        'abdominal cramps',
        'nausea',
        'chills',
        'back or side pain',
    ],
    'Chronic kidney disease': [
        'urination at small intervals in larger amounts than normal with pale color.',
        'less urination than usual with dark color.',
        'blood in urine.',
        'swelling in face, hands, feet, legs, and ankles.',
        'nausea and vomiting.',
        'loss of appetite.',
        'shortness of breath.',
        'chest pain.',
    ],
    
    # Diseases starting with "D"
    
    'Dandruff': [
        'dry scalp',
        'seborrheic dermatitis',
        'dandruff',
    ],
    'Dementia': [
        'frequent and progressive loss of memory',
        'difficulty in completing similar tasks',
        'communication problems',
        'getting lost on previously familiar streets',
        'poor judgment',
        'problems dealing with money',
        'misplacing things',
        'mood changes',
        'personality changes',
        'loss of creativity',
    ],
    'Dengue fever': [
        'high fever up to 104°f',
        'bone, joint, and muscle pain',
        'headache',
        'pain in eyes',
        'nausea and vomiting',
        'bleeding from nose and mouth',
        'severe abdominal pain',
        'damage to liver, lungs, and heart',
    ],
    'Dental black triangle': [
        'black triangle in between the teeth',
        'black spots on teeth',
    ],
    'Dermatitis': [
        'redness on skin',
        'inflammation of skin',
        'itching in the skin',
        'dry and flaky skin',
        'rough and thickened skin',
        'itchy blisters appear',
        'lichenification',
        'tiny fluid-filled blisters may be seen under the skin',
        'blisters burst, fluid oozes onto the surface',
        'crusts or scabs formed when the fluid dries',
    ],
    'Deviated Nasal Septum (DNS)': [
        'obstruction of one or both nostrils',
        'nose bleeding',
        'noisy breathing during sleep',
        'sinus infections',
        'sleep apnea',
        'facial pain',
        'whistling sounds while inhaling or exhaling',
        'nasal blockage is more intense on one side',
        'repetitive sneezing',
        'mild to severe loss of smell',
        'snoring',
    ],
    'Diabetes Mellitus': [
        'increased thirst',
        'frequent urination',
        'extreme hunger',
        'blurred vision',
        'slow-healing sores',
        'presence of ketones in the urine',
        'weight loss',
        'skin pigmentation',
    ],
    'Diabetic neuropathy': [
        'numbness and tingling sensation',
        'burning sensation',
        'severe pain and cramps',
        'loss of balance and coordination',
        'muscle weakness',
        'foot problems like ulcers, sores, and severe deformities',
    ],
    'Diarrhea': [
        'weight loss',
        'fever',
        'blood or pus in the stools',
        'persistent vomiting',
        'dehydration',
        'stomach pain',
        'abdominal cramps',
        'bloating',
        'thirst',
    ],
    'Dizziness': [
        'feeling of getting faint or lightheadedness',
        'false sensation of spinning or whirling',
        'loss of balance and feeling of floating',
        'sweating, nausea, or vomiting',
        'shortness of breath',
        'headache and confusion',
        'pain, pressure-like feeling in the back, neck, jaw, or upper belly or in one or both shoulders or arms',
        'sudden weakness in the body',
        'fast or irregular heartbeat',
        'difficulty in walking',
        'staggering gait and loss of coordination (ataxia)',
        'infrequent eye movements, such as flitting of the eyes (nystagmus)',
    ],
    'Down Syndrome': [
        'flat and small head',
        'protruding tongue too large for the mouth',
        'eyes slanted upwards with white spots on the iris',
        'small nose with a flat nasal bridge',
        'broad hands with short fingers',
        'short and odd-shaped ears',
        'palm characterized by only one crease across it',
        'poor muscle tone',
        'wide space between the first and second toe (sandal gap)',
        'height and weight usually below average',
    ],
    'Duodenal Ulcers': [
        'pain in the stomach relieved by eating or drinking milk',
        'sensation of fullness and bloating',
        'heartburn due to reflux of acid',
        'nausea',
    ],
    'Dysfunctional Uterine Bleeding (DUB)': [
        'heavy menstrual bleeding',
        'bleeding that lasts for more than one week',
        'excessive bleeding between periods',
        'bleeding with spots',
        'bloating',
        'tenderness in the breast',
    ],
    'Dysphagia': [
        'coughing while swallowing food',
        'choking of the throat',
        'throat gagging',
        'complications in passing food or liquid through the esophagus on the first try',
        'obstruction in the throat and esophagus',
        'pain while swallowing food',
        'food or liquid regurgitation after swallowing through the mouth, nose, or throat',
        'weight loss',
        'heartburn',
        'chest pain',
        'pressure in the chest region',
    ],

    
    # Diseases starting with "E"

'Eczema': [
    'dry, sensitive skin',
    'intense itching',
    'scaly areas',
    'oozing or crusting',
    'recurring rashes',
    'dark-colored patches of skin',
    ],

'Edema': [
    'puffiness or swelling of tissues under the skin',
    'oncrease in abdomen size',
    'stretched skin',
    'shortness of breath',
    'chest pain',
    'difficulty in breathing',
    ],

'Endometriosis': [
    'dysmenorrhea (Painful periods): Pelvic pain and cramping starting a few days before the menstrual period and may also include lower back and abdominal pain',
    'pain during Intercourse: Pain during or after sex due to endometriosis',
    'pain with urination and bowel movements: Pain during passing urine or bowel movements',
    'excessive Bleeding: Heavy bleeding (menorrhagia) and bleeding between periods (menometrorrhagia)',
    'infertility: One of the main reasons for infertility',
    ],

'Eosinophilia': [
    'frequent wheezing',
    'breathlessness',
    'abdominal pain',
    'diarrhea',
    'fever',
    'cough',
    'skin rashes',
    ],

'Epilepsy': [
    'sudden jerks in arms',
    'strange feeling',
    'sudden blackout and fainting',
    'stiffness in muscles',
    'twitching or trembling of muscles',
    'psychic symptoms',
    ],

'Erectile Dysfunction': [
    'trouble in getting an erection',
    'difficulty in keeping an erection',
    'reduced sexual desire',
    ],

'Evans Syndrome': [
    'bleeding can happen from any part of the body like nose (epistaxis), oral cavity, eyes, hair follicles, etc.',
    'bruises (blue spots) may be localized or generalized',
    'petechiae: Tiny red dots that can appear at any part of the body',
    'weakness',
    'vertigo',
    'headache',
    'skin pallor (due to anemia)',
    'fatigue',
    'shortness of breath',
    'tachycardia (rapid heartbeat)',
    'recurrent infections',
    'weight loss',
    'emotional distress and irritability',
    ],

# Diseases starting with "D"

'Fatty Liver': [
    'pain in the center or right upper part of the belly',
    'feeling of tiredness',
    'loss of weight or poor appetite',
    'weakness',
    'enlarged spleen',
    'abdominal swelling (ascites)',
    'yellowing of the skin and eyes (jaundice)',
    'nausea',
    'skin on neck or under your arms may have dark-colored patches',
    'confusion, poor judgment, or trouble in concentration may also happen',
    ],

'Fibroid': [
    'heavy menstrual cycles',
    'complications in pregnancy',
    'pain in pelvic area',
    'frequent urination',
    'pressure imposed on the rectum so problems of constipation can occur',
    'anemia due to blood loss',
    'pain in legs and back',
    'infertility may occur in women due to changes in the lining of the uterus',
    ],

'Fibromyalgia': [
    'constant dull ache that has',
    'pain on both sides of the body',
    'pain above waist',
    'pain below waist',
    'tiredness',
    'insomnia',
    'fibro fog',
    'adhd',
    'headache',
    'depression',
    'pain in the lower abdomen',
    ],

'Flu': [
    'fever',
    'high fever',
    'body aches especially in arms, legs, and back',
    'coughing',
    'sore throat',
    'running nose or nasal congestion',
    'fever with chills',
    'weakness and fatigue',
    ],

'Food Poisoning': [
    'abdominal pain',
    'diarrhea',
    'bloody diarrhea',
    'vomiting',
    'nausea',
    'fever and Chills',
    'loss of appetite',
    'dehydration',
    ],

'Frozen Shoulder': [
    'pain and stiffness which makes movement restricted',
    'dull and hurting pain in the shoulder',
    'sensation in the upper arm',
    ],

'Fungal Aspergillosis': [
    'fever',
    'cough with blood',
    'wheezing',
    'weight loss',
    'chills',
    'chest pain',
    'phlegm',
    'shortness of breath',
    'skin sores',
    ],

'Fungal Candidiasis': [
    'redness in the mouth area',
    'difficulty in swallowing',
    'sore throat',
    'cracks at the corner of the mouth',
    'itching in the vaginal area',
    'redness and soreness in the vaginal area',
    'vaginal discharge which has the appearance like cottage cheese',
    'pain during sexual intercourse',
    'red rash on the penis',
    'itching on the penis',
    'burning sensation on the penis',
    ],

# Diseases starting with "G"

'Gangrene': [
    'Discoloration of skin like from pale to black, purple, blue, bronze, and red',
    'A clear difference is visible between healthy and damaged skin',
    'Intense pain',
    'Numbness',
    'Foul-smelling discharge from the wound',
    'Painful and swollen tissues',
    'Low blood pressure',
    'Increased heart rate',
    'Shortness of breath',
    'Fever',
    'Temperature may lower down than 96.8°F',
    'Dizziness',
    ],

'Gastroparesis': [
    'Heartburn',
    'Acid reflux',
    'Abdominal pain',
    'Bloating',
    'Vomiting undigested food',
    'Nausea',
    'Feeling of fullness after eating a few bites',
    'Poor appetite',
    'Weight loss and malnutrition',
    ],

'Genital Herpes': [
    'Swelling in lymph nodes',
    'Headache',
    'Fever',
    'Muscle aches',
    'Pain in the genital areas',
    'Sores can form on the cervix, external genitals, and vaginal areas in females',
    'Sores formation occurs on the scrotum, penis, thighs, and urethra in males',
    'Sores can form on the anus, mouth, and buttocks in both males and females',
    ],

'Goitre': [
    'Swelling in the neck',
    'Difficulty breathing or swallowing',
    'Coughing and hoarseness',
    'Tight feeling in the throat',
    ],

'Gonorrhea': [
    'The first noticeable symptom in men is often a burning or painful sensation during urination and greater urgency of urination',
    'A pus-like discharge from the penis (white, yellow, beige, or greenish) or anal discharge and other symptoms like itching, pain, bleeding, or pain with passing bowel movements',
    'Swelling or redness occurs at the opening of the penis',
    'Testicles are painful and swollen',
    'Sore throat (rare)',
    'Pinkeye (conjunctivitis) (rare)',
    'Painful or frequent urge to urinate with a burning sensation',
    'Abnormal yellow or green vaginal discharge',
    'Painful sexual intercourse accompanied by abnormal vaginal bleeding or irregular menstrual bleeding',
    'Anal itching, discomfort, bleeding, or discharge',
    'Genital itching',
    'Swollen and painful glands at the opening of the vagina (Bartholin glands)',
    'Pain in the lower abdominal region',
    'Fever and general tiredness',
    'Nausea and vomiting',
    ],

'Gout': [
    'Pain',
    'Waking up early in the morning with unbearable pain',
    'Inability to put on socks and shoes',
    'Excess or absence of perspiration',
    'Severe pain on injury',
    'Laxity in joints',
    'Appearance of boils',
    'Heaviness',
    'Numbness',
    'Itching',
    'Unstable pain in joints',
    'Abnormal complexion',
    'Appearance of patches',
    ],
    
# Diseases starting with "H"

'Hair Loss': [
    'dandruff',
    'lesions of skin',
    'hair loss in patches',
    'scarring',
    'excessive hair fall daily',
    ],

'Bad Breath (Halitosis)': [
    'pain in teeth',
    'swollen gums',
    'pus in gums',
    'plaque between teeth',
    'dryness of mouth',
    'difficulty in swallowing food',
    ],

'Hearing Loss': [
    'difficulty in hearing others clearly and error in hearing what they say, especially in a group',
    'difficulty in understanding words, especially if there is background noise or in a crowd of people',
    'hearing consonants is tough',
    'repeatedly asking others to speak more slowly, clearly, and loudly',
    'need to turn up the volume of the television or radio',
    'avoiding some social situations',
    'ringing, roaring, or hissing sounds are heard in the ears, known as tinnitus',
    'feeling as if there is water or pressure in the ear',
    ],

'Heartburn': [
    'a burning pain in the chest that usually occurs after eating or may occur at night',
    'pain;,
    'pain that worsens on lying down or bending down',
    'difficulty in swallowing',
    'chronic cough',
    'sore throat',
    'persistent nausea and vomiting',
    'regurgitation of the foods and liquids with a taste of acid in the throat',
    ],

'Heart Diseases': [
    'discomfort and pain in breastbone, arm, and chest',
    'heartburn and indigestion',
    'feeling of drowsiness, vomiting, nausea, and sweating',
    'fluctuation in heartbeat',
    'weakness in the whole body',
    'difficulty in breathing',
    'fainting',
    'myocardial infarction may occur in the case of diabetes patients',
    'discomfort in the chest, feeling heavy pressure in the chest',
    'swelling in ankles, legs, and abdomen',
    'rapid weight gain',
    'white sputum in cough',
    'shortness of breath after normal activities',
    'pressure in the upper back',
    ],

'Hemorrhoids (Piles)': [
    'bleeding while going to the toilet',
    'bleeding while passing stool',
    'painless, bright red rectal bleeding during or following a bowel movement',
    'blood typically covers the stool',
    'mucous discharge',
    'perianal mass if they prolapse through the anus',
    'iItchiness or fecal incontinence',
    'blood clot',
    'anal pain',
    'anal bulging',
    ],

'Henoch-Schonlein Purpura (HSP)': [
    'reddish-purple colored spots',
    'bruises',
    'rashes',
    'pain',
    'swelling around the joints',
    'swelling knees',
    'swelling ankles',
    'abdominal pain',
    'bloody stools',
    'stomach ache',
    ],

'Hepatitis B': [
    'fever',
    'belly pain',
    'nausea and vomiting',
    'dark colored urine',
    'feeling tired',
    'headache',
    'pain in joints',
    'jaundice',
    'pale, clay-colored stool',
    'hives',
    'loss of appetite',
    ],

'Inguinal Hernia': [
    'bulge near the pubic bone',
    'burning sensation at the bulge',
    'pain in the groin area',
    'heavy sensation in your groin',
    'pain and swelling around the testicles when intestines descend into the scrotum',
    'weakness or pressure in the groin area',
    ],

'Umbilical Hernia': [
    'soft swelling near the umbilicus',
    'bulge near the umbilicus',
    'swelling in umbilicus',
    'bulge in umbilicus',
    ],

'Femoral Hernia': [
    'pain',
    'discomfort',
    'bulge may be visible in the groin area',
    ],

'Diaphragmatic Hernia': [
    'pain',
    'nausea',
    'vomiting',
    'discomfort',
    'heartburn',
    'belching',
    'chest pain',
    ],

'Hiatal Hernia': [
    'heartburn',
    'belching',
    'chest pain',
    'nausea',
    ],

'Incisional Hernia': [
    'a bulge or protrusion',
    'pain',
    'discomfort',
    ],

'Herpes Zoster (Shingles)': [
    'fluid-filled blisters follow rash which then break open and crust over',
    'pain',
    'burning skin',
    'numbness',
    'tingling',
    'rash sensitivity to touch',
    'a red rash 2-3 days after the pain',
    'rashes',
    'fever',
    'chills',
    'fatigue',
    'muscle weakness',
    'headache',
    'sensitivity to light',
    'joint Pain',
    'swollen glands',
    'hearing loss',
    'loss of eye motion',
    'taste Problems',
    'vision Problem',
    ],

'Cholesterol Problems': [
    'angina',
    'heart attack',
    'stroke',
    'pain on walking',
    ],

'Hypertension (High Blood Pressure)': [
    'headache (at the back of the head in the morning)',
    'vertigo',
    'tinnitus',
    'fainting episodes',
    ],

'Hyperthyroidism': [
    'increased appetite',
    'weakness',
    'nervousness',
    'nausea',
    'vomiting',
    'irregular heartbeat',
    'elevated blood pressure',
    'restlessness',
    'inability to concentrate',
    'hair loss',
    'itching',
    'weight loss',
    'cold intolerance',
    ],

'Hypocortisolism (Addison\'s Disease)': [
    'weakness in muscles',
    'loss of appetite',
    'fatigue',
    'decreased blood sugar (hypoglycemia)',
    'nausea',
    'diarrhea',
    'muscle pain',
    'joint pain',
    'craving for salty things',
    'hair loss',
    'depression',
    'sexual dysfunction in females',
    'weight loss',
    'skin darkening (hyperpigmentation)',
    ],

'Hyponatremia': [
    'headache',
    'nausea',
    'vomiting',
    'dizziness',
    'loss of energy',
    'drowsiness',
    'fatigue',
    'muscle weakness',
    'spasms',
    'seizures',
    'restlessness',
    'irritability',
    'coma',
    ],

'Hypotension (Low Blood Pressure)': [
    'faintness',
    'dizziness',
    'Fatigue',
    'nausea',
    'lack of concentration',
    'blurred vision',
    'stress',
    'cold body',
    'pale skin',
    'calmness',
    'confusion',
    'rapid breathing',
    'shallow breathing',
    'rapid pulse rate',
    'weak pulse rate',
    ],

'Hypothyroidism': [
    'weakness and fatigue',
    'dry and coarse hair',
    'rough and pale skin',
    'hair loss',
    'frequent muscle cramps',
    'sudden weight gain',
    'cold intolerance',
    ],

    # Add more diseases and symptoms here
}



# User-entered symptom
user_symptom = input("Enter a symptom: ")
user_symptom = user_symptom.lower()

# Create a list of unique diseases based on the symptom
unique_diseases = []

for disease, symptoms in disease_symptoms.items():
    if user_symptom in symptoms:
        unique_diseases.append(disease)

# Ask follow-up questions for each unique disease
for disease in unique_diseases:
    print(f"Symptom: {user_symptom} is associated with {disease}.")

    # Display the other symptoms for the disease
    other_symptoms = ", ".join(symptoms)
    print(f"Other symptoms for {disease}: {other_symptoms}")

    # Ask if the user has the rest of the symptoms to confirm the disease
    confirm_symptoms = input(f"Do you have the rest of the symptoms for {disease}? (yes/no): ").lower()
    
    if confirm_symptoms == 'yes':
        print(f"You are confirmed to have {disease}.")
    else:
        print(f"It is possible that you might have {disease}.")

# Example follow-up questions for each disease (customize as needed)
if 'Abnormal Heart Rhythms (Arrhythmia)' in unique_diseases:
    print("Ask follow-up questions for Abnormal Heart Rhythms (Arrhythmia).")
    # Add more specific questions related to this disease
if 'Acidity' in unique_diseases:
    print("Ask follow-up questions for Acidity.")
    # Add more specific questions related to this disease
# Add more follow-up questions for other diseases as needed
