# Sample dictionary of diseases and their symptoms
disease_symptoms = {
    
    # Diseases starting with "A"
    
    'Abnormal Heart Rhythms (Arrhythmia)': [
        'Shortness of breath',
        'Chest pain',
        'Irregular pulse',
        'Heart palpitations',
        'Sweating',
        'Pale color of skin',
    ],
    'Acidity': [
        'Nausea',
        'Burning sensation in the chest',
        'Burping',
        'Vomiting tendency',
        'Chest pain',
        'Sensation of a lump in your throat',
        'Difficulty swallowing',
        'Bloating',
        'Severe pain in the stomach',
        'Difficulty in breathing when acidity is at the acute stage',
        'Due to hyper acidity there is erosion of gum and teeth',
        'Bad breath',
    ],
    'Acid Reflux': [
        'Heartburn',
        'Regurgitation',
        'Gas bloating',
        'Bloody or black colored stools',
        'Bloody vomiting',
        'Burping and Hiccups',
        'Dysphagia i.e. difficulty in swallowing',
        'Nausea',
        'Unexpected weight loss',
        'Wheezing (The sound of a high-pitched whistle while breathing)',
        'Dry cough',
        'Hoarseness or chronic sore throat',
    ],
    'Acne': [
        'Whiteheads or the closed plugged pores',
        'Blackheads or open plugged pores',
        'Small and red colored tender bumps on the affected area',
        'Pimples with pus at their tips',
        'Large painful lumps that are present beneath the skin surface',
        'Presence of pus-filled lumps beneath the surface of the skin, also known as cystic lesions',
    ],
    'Agoraphobia': [
        'Rapid breathing',
        'Rapid heartbeat',
        'Excessive sweating',
        'Feeling too much hot',
        'Feeling sick',
        'Tingling sensation and numbness',
        'Pain in the chest',
        'Dizziness or light-headedness',
        'Chills and sudden flushes',
        'Diarrhea',
        'Upset stomach',
        'Fear of death',
        'Losing control',
        'Afraid to be alone',
        'Afraid to be in the crowd',
        'Scared to leave home alone',
        'Too much dependence on others',
        'Feeling of helplessness',
        'Loss of sanity',
        'Fear of staying alone',
        'Feeling of anxiety and fear',
        'Always staying at home',
        'Always feeling the need to be with a trusted individual',
    ],
    'Allergic Bronchitis': [
        'Mucus-producing cough (clear mucus or white)',
        'Recurring morning cough',
        'Fatigue',
        'Sinus congestion or Postnasal drip',
        'Bad breath (Halitosis)',
        'Wheezing/ whistling sound during breathing',
        'Shortness of breath (Dyspnea)',
        'Chest tightness',
    ],
    'Allergic Rhinitis': [
        'Sneezing',
        'Running nose',
        'Itching on the nose, eyes as well as on the roof of the mouth',
        'Conjunctivitis- Redness and swelling in the eyes',
    ],
    'Food allergy': [
        'Swelling in the lips, tongue as well as on the face',
        'Hives',
        'Tingling mouth',
        'Anaphylaxis',
        'Throat swelling',
    ],
    'Insect sting allergy': [
        'Swelling on the sting site',
        'Itching all over the body',
        'Hives',
        'Cough and chest tightness',
        'Anaphylaxis',
        'Wheezing or shortness of breath',
    ],
    'Drug allergy': [
        'Hives',
        'Itching all over the skin',
        'Rash as well as redness',
        'Swelling on the face',
        'Shortness of breath',
    ],
    'Skin Allergy': [
        'Itching',
        'Redness',
        'Rashes',
        'Flake or peel of skin',
    ],
    'Alopecia (Hair Loss)': [
        'Presence of Circular patches or bald spots',
        'Sudden loss of hair',
        'Thinning of hair',
        'Partial or full body hair loss',
    ],
    'Alzheimer\'s Disease': [
        'Loss of memory',
        'Difficulty in concentrating and thinking',
        'Difficulty in performing daily basic tasks such as bathing or dressing etc.',
        'Changes in personality',
        'Changes in behavior',
        'Depression and mood swings',
        'Wandering',
        'Aggressive behavior',
        'Irritation',
    ],
    'Amyloidosis': [
        'Swelling in the ankles and legs',
        'Fatigue',
        'Weakness',
        'Shortness of breath',
        'Diarrhea and constipation',
        'Pain in hands and feet',
        'An enlarged tongue',
        'Feeling of fullness after eating',
        'An irregular heartbeat',
        'Skin discoloration',
        'Weight loss',
    ],
    'Anaemia': [
        'Tiredness and weakness on little exertion',
        'Paleness and dullness of skin',
        'Shortness of breath',
        'Increase in heartbeat',
        'Confusion and dizziness',
        'Insomnia',
        'Cold and clammy hands',
        'Body aches',
        'Fatigue',
        'Restlessness',
        'Lack of Energy',
        'Irritable Behavior',
    ],
    'Anal Fistula': [
        'Pain which is usually throbbing, constant, worsen in sitting position',
        'Discharge of pus and blood',
        'Constipation or pain associated with bowel movement',
        'Fever',
    ],
    'Anemia': [
        'Pale skin',
        'Weakness',
        'Fatigue',
        'Tiredness',
        'Chest pain',
        'Chest pain',
        'Headache',
    ],
    'Angina Pectoris': [
        'Nausea',
        'Sweating',
        'Fatigue',
        'Breathlessness',
        'Anxiety',
        'Dizziness',
        'Discomfort and pain in back, neck and shoulders',
        'Chest pain',
    ],
    'Ankylosing Spondylitis': [
        'Pain and stiffness in lower back and hip region',
    ],
    'Anorexia nervosa': [
        'Refuse to eat certain food',
        'Constipation',
        'Abdominal pain',
        'Cold intolerance',
        'Not feeling hungry often',
        'Weight loss',
        'Cooks meals for others without eating',
        'Limited social spontaneity',
        'Intense fear of weight gain',
        'Shows flexible thinking',
        'Follows strict diet and exercise routine',
        'Dry skin',
        'Dry and brittle nails',
        'Fine hair on body',
        'Muscle weakness',
        'Feeling cold all the time',
        'Fainting, sleep problems, feeling dizziness all the time',
        'Difficulty in concentrating',
        'Poor immune system',
        'Thinning of hair on head',
    ],
    'Anxiety': [
        'Improper sleep',
        'Muscle tension',
        'Chronic indigestion',
        'Stage fear',
        'Self consciousness',
        'Panic',
        'Flashbacks',
        'Perfectionism',
        'Compulsive behavior',
        'Self-doubt',
    ],
    'Arthritis': [
        'Pain in the joints',
        'Inflammation in the joints',
        'Stiffness, swelling, redness and warmth in the joints',
        'Tenderness in the inflamed joints',
        'Sometimes, fever, weight loss and fatigue',
    ],
    'Ascites': [
        'Increased abdominal girth and size',
        'Pain in the abdomen',
        'Discomfort and bloating',
    ],
    'Asherman\'s Syndrome': [
        'Menstrual irregularities such as very light periods (hypo menorrhea) or absence of periods (amenorrhea)',
        'May lead to Infertility due to adhesions including the uterus and fallopian tubes',
        'Recurrent pregnancy loss (miscarriage)',
        'Pelvic pain, if scar tissue blocks the outflow of the menstrual blood, causing uterine cramping and pelvic discomfort or pain',
    ],
    'Asthma': [
        'Coughing - Coughing from asthma worsen at night and early in the morning, and make it hard to sleep',
        'Wheezing - Wheezing is a whistling sound occurs when you breathe',
        'Chest tightness - This may feel like something is squeezing your chest',
        'Shortness of breath - Someone who have asthma cannot catch their breath, you may feel like you cannot get air out of your lungs',
        'Trouble in sleeping due to wheezing, chest tightness and coughing',
        'Not all people who have asthma have these symptoms, having these symptoms not always means that you have asthma. Sometimes symptoms just annoy you, or troublesome to your daily routine',
        'Severe Symptoms can be fatal. It\'s important to treat symptoms when you first notice them otherwise they become fatal',
    ],
    'Atopic Dermatitis': [
        'Itching, which can be severe, at night especially',
        'Red to brownish-gray patches, especially on the neck, upper chest, eyelids, inside the bend of the elbows hands, feet, ankles, wrists, and knees. In the case of infants, these patches form on face and scalp',
        'Burning sensation or pain on the skin',
        'Skin becomes dry, red, scaly, thickened and rough',
        'Fissures in the skin',
        'Inflammation of the skin',
        'Lumps formed on skin and there is the leakage of fluid',
    ],
    'Atrial Fibrillation': [
        'Rapid heart rate',
        'Heart palpitations',
        'Shortness of breath (while lying flat or sudden onset during night)',
        'Light headedness',
        'Dizziness',
        'Confusion',
        'Fainting',
        'Chest pain',
        'Increased risk for heart failure, dementia and stroke',
        'Swelling in lower extremities',
        'Respiratory distress due to congestion of lungs',
    ],
    'Autism': [
        'Lines up toys or other objects',
        'Plays with toys the same way every time',
        'Has to follow certain routines',
        'Likes parts of objects',
        'Is very organized',
        'Flaps hands, rocks body, or spins self in circles',
        'Does not point or respond to pointing',
        'Does not understand jokes or teasing',
        'Talks in a flat, robot-like, or sing-song voice',
        'Gives unrelated answers to questions',
        'Delayed speech and language skills',
        'Uses few or no gestures (e.g., does not wave goodbye)',
    ],
    'Autoimmune Disorder': [
        'Fever',
        'Fatigue',
        'Joint pain',
        'Malaise',
    ],
    
    # Diseases starting with "B"
    
    'Back Pain': [
        'Weight loss',
        'Fever',
        'Inflammation or swelling on the back',
        'Pain down the legs',
        'Pain that reaches below the knees',
        'Difficulty urinating',
        'Recent injury to the back',
        'Back pain which causes difficulty in lying down',
        'Numbness around the genitals',
        'Numbness around the buttocks',
        'Numbness around the anus',
    ],
    'Bacterial Vaginosis': [
        'Vaginal discharge',
        'Vaginal odor',
        'Itching around the vagina',
        'Burning sensation while urination',
    ],
    'Baldness': [
        'Hair loss in patches',
        'Dandruff',
        'Skin lesions',
        'Scarring',
        'Thinning of hair',
    ],
    'Bedwetting': [
        'Passing urine during day or night sleep',
    ],
    'Bell\'s Palsy': [
        'Facial paralysis and no control over facial muscles',
        'Unable to taste or loses sense of taste',
        'Feeling weakness of the muscles and nerves in the facial region',
        'Difficulty in closing eyes',
        'Pain in and outside ears',
        'Numbness of the jaws, forehead, cheek, mouth region',
        'Blurred view',
        'In an attempt to raise eyebrows, the forehead region affected by Bell\'s palsy remains flat',
        'Smiling distorts the face of the patient',
    ],
    'Benign Prostatic Hyperplasia (BPH)': [
        'Urinary frequency',
        'Urinary urgency',
        'Hesitancy',
        'Incomplete bladder emptying',
        'Straining',
        'Disturbed sleep at night',
        'Decreased force of stream',
        'Dribbling',
    ],
    'Wet Beriberi': [
        'Increase in heart rate',
        'Swollen lower legs',
        'Waking up short of breath',
        'Shortness of breath during physical activity',
    ],
    'Dry Beriberi': [
        'Paralysis',
        'Involuntary eye movement',
        'Vomiting',
        'Difficulty in breathing',
        'Pain',
        'Mental confusion',
        'Tingling in feet and hands',
        'Decreased muscle function',
    ],
    'Bipolar Mania': [
        'Excitement',
        'Talkativeness',
        'Impulsive behavior',
        'Overactivity',
        'Racing thoughts',
        'Reduced need for sleep',
    ],
    'Bipolar Hypomania': [
        'Aggression or anger',
        'Overconfidence',
        'Irritability',
        'Decreased need for sleep',
        'Hyperactivity',
    ],
    'Bipolar Depression': [
        'Sadness',
        'Hopelessness',
        'Loss of interest or pleasure in most activities',
        'Fatigue',
        'Difficulty concentrating',
        'Change in appetite or weight',
        'Thoughts of death or suicide',
    ],
    'Bipolar Mixed Episodes': [
        'Symptoms of both mania and depression occurring simultaneously',
        'Agitation',
        'Irritability',
        'Trouble sleeping',
        'Change in appetite or weight',
    ],
    'Blood Clotting': [
        'Swelling',
        'Pain',
        'Tenderness',
        'Redness',
        'Warm sensation',
    ],
    'Blood Disorders': [
        'Blood clot (Phlebitis)',
        'Skin rashes caused by few platelets (Petechiae)',
        'Blood blisters in mouth',
        'Swelling of lymph nodes due to blood cancer like leukemia, lymphomas',
        'Yellowish skin (Pallor) caused by anemia',
        'Eating of ice, dirt, clay (Pica) due to iron deficiency anemia',
    ],
    'Bronchitis': [
        'Constant cough with mucus',
        'Difficulty in breathing',
        'Fever',
        'Wheezing',
        'Chest discomfort',
    ],
    'Bulged Disc': [
        'Pain in arms and legs',
        'Numbness',
        'Weakness',
    ],

    # Diseases starting with "C"
    
    'Cancer': [
        'Fever',
        'Fatigue',
        'Pain',
        'Unusual bleeding',
        'Nagging cough',
        'Indigestion problems or trouble swallowing.',
        'Unexplained weight loss',
        'Skin changes',
    ],
    'Candidiasis': [
        'Redness',
        'Itching',
        'Swelling',
        'Rashes',
        'Burning sensation',
    ],
    'Cataract': [
        'Blurred vision',
        'Difficulty with vision at night',
        'Double vision',
        'Problem differentiating colors',
        'Sensitivity to light',
        'Seeing "halos" around lights',
        'Fading or yellowing of colors',
        'Frequent changes in eyeglass or contact lens prescription',
    ],
    'Cerebral Palsy': [
        'Difficulty in movement',
        'Ataxia (lack of muscle coordination)',
        'Variation in muscle tone',
        'Involuntary movements',
        'Rigidity',
        'Problem in feeding and sucking',
        'Difficulty in eyesight, hearing or speaking',
        'Athetosis (slow, writhing problems)',
        'Spasticity (severe tightening of muscle)',
    ],
    'Cerebral Stroke': [
        'Depression',
        'Double vision',
        'Headache',
        'Dizziness',
        'Weakness on one or both sides of the body',
        'Trouble in walking, speaking or understanding',
        'Paralysis on face',
    ],
    'Cervical Dystonia': [
        'Cramps in the legs',
        'Neck pull involuntarily',
        'Blinking of the eyes in an uncontrolled manner',
        'Difficulties in speech',
        'Dragging of legs',
        'Fatigue',
        'Exhaustion',
        'Stress',
        'Pain',
    ],
    'Cervical Spondylosis': [
        'Standing',
        'Sitting',
        'Sneezing',
        'Coughing',
        'Tilting your neck backward',
    ],
    'Cholera': [
        'Rice water stools',
        'Leg cramps',
        'Vomiting',
        'Loose skin',
        'Sunken eyes',
        'Fast heart beat',
        'Low blood pressure',
        'Massive weight loss',
        'Dry mouth',
        'Collapse of the circulatory system',
    ],
    'Chronic Fatigue Syndrome': [
        'Muscle pain',
        'Fatigue',
        'Memory loss',
        'Confusion',
        'Anxiety and depression',
        'Stroke',
        'Trauma',
        'Joint pain',
    ],
    'Constipation': [
        'Pain during passing stool',
        'Bleeding during stools',
        'Abdominal pain',
        'Indigestion',
        'Heaviness of body',
        'Loss of appetite',
        'Dry and difficult bowel movement',
        'Feeling uncomfortable',
    ],
    'Crohn\'s Disease': [
        'Diarrhea',
        'Fatigue',
        'Abdominal pain',
        'Abdominal cramps',
        'Loss of appetite',
        'Weight loss',
        'General weakness',
        'Fever',
        'Mucus',
        'Pain and drainage around the anal region',
        'Mouth sores',
        'Blood in stool',
        'It may cause inflammation of eyes, skin, and joints.',
        'In children, it leads to delayed growth or sexual development.',
        'Sometimes it may cause inflammation of the liver and bile ducts.',
    ],
    'Cystitis': [
        'Frequent urge of urination',
        'Burning sensation while urinating',
        'Fever',
        'Blood in urine (hematuria)',
        'Pain during sexual intercourse',
        'Pressure on the lower abdomen',
        'Cloudy and strong-smelling urine',
        'Abdominal cramps',
        'Nausea',
        'Chills',
        'Back or side pain',
    ],
    'Chronic Kidney Disease': [
        'Urination at small intervals in larger amount than normal with pale color.',
        'Less urination than usual with dark color.',
        'Blood in urine.',
        'Swelling in face, hands, feet, legs, and ankles.',
        'Nausea and vomiting.',
        'Loss of appetite.',
        'Shortness of breath.',
        'Chest pain.',
    ],
    
    # Diseases starting with "D"
    
    'Dandruff': [
        'Dry scalp',
        'Seborrheic dermatitis',
        'Dandruff',
    ],
    'Dementia': [
        'Frequent and progressive loss of memory',
        'Difficulty in completing similar tasks',
        'Communication problems',
        'Getting lost on previously familiar streets',
        'Poor judgment',
        'Problems dealing with money',
        'Misplacing things',
        'Mood changes',
        'Personality changes',
        'Loss of creativity',
    ],
    'Dengue Fever': [
        'High fever up to 104°F',
        'Bone, joint, and muscle pain',
        'Headache',
        'Pain in eyes',
        'Nausea and vomiting',
        'Bleeding from nose and mouth',
        'Severe abdominal pain',
        'Damage to liver, lungs, and heart',
    ],
    'Dental Black Triangle': [
        'Black triangle in between the teeth',
        'Black spots on teeth',
    ],
    'Dermatitis': [
        'Redness on skin',
        'Inflammation of skin',
        'Itching in the skin',
        'Dry and flaky skin',
        'Rough and thickened skin',
        'Itchy blisters appear',
        'Lichenification',
        'Tiny fluid-filled blisters may be seen under the skin',
        'Blisters burst, fluid oozes onto the surface',
        'Crusts or scabs formed when the fluid dries',
    ],
    'Deviated Nasal Septum (DNS)': [
        'Obstruction of one or both nostrils',
        'Nose bleeding',
        'Noisy breathing during sleep',
        'Sinus infections',
        'Sleep apnea',
        'Facial pain',
        'Whistling sounds while inhaling or exhaling',
        'Nasal blockage is more intense on one side',
        'Repetitive sneezing',
        'Mild to severe loss of smell',
        'Snoring',
    ],
    'Diabetes Mellitus': [
        'Increased thirst',
        'Frequent urination',
        'Extreme hunger',
        'Blurred vision',
        'Slow-healing sores',
        'Presence of ketones in the urine',
        'Weight loss',
        'Skin pigmentation',
    ],
    'Diabetic Neuropathy': [
        'Numbness and tingling sensation',
        'Burning sensation',
        'Severe pain and cramps',
        'Loss of balance and coordination',
        'Muscle weakness',
        'Foot problems like ulcers, sores, and severe deformities',
    ],
    'Diarrhea': [
        'Weight loss',
        'Fever',
        'Blood or pus in the stools',
        'Persistent vomiting',
        'Dehydration',
        'Stomach pain',
        'Abdominal cramps',
        'Bloating',
        'Thirst',
    ],
    'Dizziness': [
        'Feeling of getting faint or lightheadedness',
        'False sensation of spinning or whirling',
        'Loss of balance and feeling of floating',
        'Sweating, nausea, or vomiting',
        'Shortness of breath',
        'Headache and confusion',
        'Pain, pressure-like feeling in the back, neck, jaw, or upper belly or in one or both shoulders or arms',
        'Sudden weakness in the body',
        'Fast or irregular heartbeat',
        'Difficulty in walking',
        'Staggering gait and loss of coordination (ataxia)',
        'Infrequent eye movements, such as flitting of the eyes (Nystagmus)',
    ],
    'Down Syndrome': [
        'Flat and small head',
        'Protruding tongue too large for the mouth',
        'Eyes slanted upwards with white spots on the iris',
        'Small nose with a flat nasal bridge',
        'Broad hands with short fingers',
        'Short and odd-shaped ears',
        'Palm characterized by only one crease across it',
        'Poor muscle tone',
        'Wide space between the first and second toe (sandal gap)',
        'Height and weight usually below average',
    ],
    'Duodenal Ulcers': [
        'Pain in the stomach relieved by eating or drinking milk',
        'Sensation of fullness and bloating',
        'Heartburn due to reflux of acid',
        'Nausea',
    ],
    'Dysfunctional Uterine Bleeding (DUB)': [
        'Heavy menstrual bleeding',
        'Bleeding that lasts for more than one week',
        'Excessive bleeding between periods',
        'Bleeding with spots',
        'Bloating',
        'Tenderness in the breast',
    ],
    'Dysphagia': [
        'Coughing while swallowing food',
        'Choking of the throat',
        'Throat gagging',
        'Complications in passing food or liquid through the esophagus on the first try',
        'Obstruction in the throat and esophagus',
        'Pain while swallowing food',
        'Food or liquid regurgitation after swallowing through the mouth, nose, or throat',
        'Weight loss',
        'Heartburn',
        'Chest pain',
        'Pressure in the chest region',
    ],
    # Add more diseases and symptoms here
}

# User-entered symptom
user_symptom = input("Enter a symptom: ")

# Create a list of unique diseases based on the symptom
unique_diseases = []

for disease, symptoms in disease_symptoms.items():
    if user_symptom in symptoms:
        unique_diseases.append(disease)

# Ask follow-up questions for each unique disease
for disease in unique_diseases:
    print(f"Symptom: {user_symptom} is associated with {disease}.")

    # Display the other symptoms for the disease
    other_symptoms = ", ".join(symptoms)
    print(f"Other symptoms for {disease}: {other_symptoms}")

    # Ask if the user has the rest of the symptoms to confirm the disease
    confirm_symptoms = input(f"Do you have the rest of the symptoms for {disease}? (yes/no): ").lower()
    
    if confirm_symptoms == 'yes':
        print(f"You are confirmed to have {disease}.")
    else:
        print(f"It is possible that you might have {disease}.")

# Example follow-up questions for each disease (customize as needed)
if 'Abnormal Heart Rhythms (Arrhythmia)' in unique_diseases:
    print("Ask follow-up questions for Abnormal Heart Rhythms (Arrhythmia).")
    # Add more specific questions related to this disease
if 'Acidity' in unique_diseases:
    print("Ask follow-up questions for Acidity.")
    # Add more specific questions related to this disease
# Add more follow-up questions for other diseases as needed
